config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :expenses do
    member do
      patch :approve
      patch :decline
    end
  end

  get 'pages/home'
  get 'user_menu', to: 'pages#user_menu'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: "users/passwords"
  }

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_menu.html.haml
#menu-container
  #menu
    = link_to root_path, id: "home-item" do
      .menu-item
        = image_tag "home.png", alt: t("images_alt.home")

    .vertical-divider

    = link_to expenses_path(type: "pending"), id: "pending-expenses-item" do
      .menu-item
        = image_tag "pending_expenses.png", alt: t("images_alt.pending_expenses")

    .vertical-divider

    = link_to expenses_path(type: "history"), id: "expenses-history-item" do
      .menu-item
        = image_tag "expenses_history.png", alt: t("images_alt.expenses_history")

    .vertical-divider

    - if current_user&.employee?
      = link_to new_expense_path, id: "add-expense-item" do
        .menu-item
          = image_tag "add.png", alt: t("images_alt.add_expense")

      .vertical-divider

    = link_to '/user_menu', id: "user-item" do
      .menu-item
        = image_tag "user.png", alt: t("images_alt.user")

app/views/shared/_modal_confirm.html.haml
.modal#modal
  %p.regular-text= message_text
  %button.btn.btn-confirm.btn-full-width{ id: button_id, type: "button" }= button_text

app/views/shared/_modal_question.html.haml
.main-center
  %p.regular-text= message_text
  %button.btn.btn-confirm.btn-half-width{id: button_yes_id}= button_yes_text
  %button.btn.btn-cancel.btn-half-width{id: button_no_id}= button_no_text