config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  resources :expenses do
    member do
      patch :approve
      patch :decline
    end
  end

  get 'pages/home'
  get 'user_menu', to: 'pages#user_menu'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: "users/passwords"
  }

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/home.html.haml
= render "devise/shared/messages", resource: nil

-# Screen content
.main-top
  %h2#user_greeting.title-text= "Bem vindo(a), #{current_user.name}!"

  #expenses-section

    - if current_user.employee?
      %h3#expenses-title.section-title-text= t('titles.my_pending_expenses')
    - if current_user.manager?
      %h3#expenses-title.section-title-text= t('titles.pending_expenses_section')

    .regular-container

      #all-expenses-box.regular-box
        %h4#all-expenses-title.subtitle-text= t('titles.all_pending_expenses')
        - if current_user.employee?
          %p#all-expenses-number.indicator-text= Expense.pending_expenses_by_employee(current_user).count
        - if current_user.manager?
          %p#all-expenses-number.indicator-text= Expense.pending_expenses_by_manager(current_user).count

      #todays-expenses-box.regular-box
        %h4#todays-expenses-title.subtitle-text= t('titles.todays_pending_expenses')
        - if current_user.employee?
          %p#todays-expenses-number.indicator-text= Expense.todays_pending_expenses_by_employee(current_user).count
        - if current_user.manager?
          %p#todays-expenses-number.indicator-text= Expense.todays_pending_expenses_by_manager(current_user).count

      #week-expenses-box.regular-box
        %h4#week-expenses-title.subtitle-text= t('titles.week_pending_expenses')
        - if current_user.employee?
          %p#week-expenses-number.indicator-text= Expense.week_pending_expenses_by_employee(current_user).count
        - if current_user.manager?
          %p#week-expenses-number.indicator-text= Expense.week_pending_expenses_by_manager(current_user).count

app/views/pages/user_menu.html.haml
.main-center
  %h2.text-primary= t("titles.user_menu")
  %h3.regular-text= current_user.name
  
  .container.container-primary.container-center-sm
    = link_to t("buttons.edit_user"), 'users/edit', class: "btn btn-primary btn-full-width"
    - if current_user.employee?
      = button_to t("buttons.delete_user"), registration_path(:user), method: :delete, class: "btn btn-primary btn-full-width"
    = button_to t("buttons.logout"), destroy_user_session_path, method: :delete, class: "btn btn-primary btn-full-width"